# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-Jho497RQtL6ejVHXpbS2DO5s-TZYkc
"""

# 📄 app.py — CityScope AI Chatbot
pip install streamlit

import streamlit as st
import pandas as pd
import joblib
from sklearn.metrics.pairwise import cosine_similarity

# === Load model and vectorizer ===
model = joblib.load("model.pkl")
vectorizer = joblib.load("vectorizer.pkl")
data = pd.read_excel("cityscopedata.xlsx")

questions = data['Question'].astype(str).tolist()
answers = data['Answer'].astype(str).tolist()

# === Streamlit UI ===
st.set_page_config(page_title="CityScope AI", layout="centered")
st.title("🏙️ CityScope AI Chatbot")

user_query = st.text_input("Ask something about Tamil Nadu's districts:")

if user_query:
    # Vectorize user query
    query_vec = vectorizer.transform([user_query])

    # Find nearest neighbor
    dist, index = model.kneighbors(query_vec, n_neighbors=1)
    matched_index = index[0][0]

    # Return answer
    st.markdown("### 🧠 Answer:")
    st.success(answers[matched_index])
